version: "2.4"
# The server profiles used in this example are intended for use with edge versions of the product image only.

#----------------------------------------------------------------------------------------
#- Ping Identity Directory & Federate Deployment
#-
#-     login  console          console           rest    ldaps
#-     9031   9999               8443            1443    1636
#-      |      |                  |               |       |
#-   +---------------+    +---------------+    +---------------+
#-   | PingFederate  |    |PingDataConsole|    | PingDirectory |
#-   +---------------+    +---------------+    +---------------+
#-
#-   +-----------------------+----------------------------------------------------------+
#-   |  Product Console/App  |  URL                                                     |
#-   |                       |    username: administrator                               |
#-   |                       |    password: 2FederateM0re                               |
#-   +-----------------------+----------------------------------------------------------+
#-   |  PingFederate         |  https://localhost:9999/pingfederate/app                 |
#-   |  PingDirectory        |  https://localhost:8443/ (Server=pingdirectory:1636)     |
#-   +-----------------------+----------------------------------------------------------+

#----------------------------------------------------------------------------------------

services:

  pingfederate:
    image: ${PING_IDENTITY_DEVOPS_REGISTRY}/pingfederate:${PING_IDENTITY_DEVOPS_TAG}
    command: wait-for pingdirectory:1389 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingfederate
    env_file:
      - ${HOME}/.pingidentity/devops
    ports:
      - "9031:9031"
      - "9999:9999"
    networks:
      - pingnet-dmz
      - pingnet-internal
    volumes:
      - pingfederate-out:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingfederate:/opt/in

  pingdirectory:
    image: ${PING_IDENTITY_DEVOPS_REGISTRY}/pingdirectory:${PING_IDENTITY_DEVOPS_TAG}
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingdirectory
    env_file:
      - ${HOME}/.pingidentity/devops
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "1636:1636"
      - "1443:1443"
      - "1389:1389"
    networks:
      - pingnet-internal
    volumes:
      - pingdirectory-out:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdirectory:/opt/in

  pingdataconsole:
    image: ${PING_IDENTITY_DEVOPS_REGISTRY}/pingdataconsole:${PING_IDENTITY_DEVOPS_TAG}
    ports:
      - "8443:8443"
    networks:
      - pingnet-internal


networks:
    pingnet-internal:
    pingnet-dmz:

volumes:
  pingfederate-haligonia-out:
  pingdirectory-haligonia-out:

